Repository pesto-students/batch-12-WeConnect, pull requests merged in 2020-02, with the labels that each got.

#11 Setup: Scaffolding
  .gitignore
  client/.gitignore
  client/README.md
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/src/__tests__/App.test.js
  client/src/actions/index.js
  client/src/assets/css/App.css
  client/src/components/app/App.js
  client/src/containers/index.js
  client/src/index.css
  client/src/index.js
  client/src/reducers/index.js
  client/src/store/index.js
  client/src/utils/index.js
  client/src/views/index.js
  client/yarn.lock
  package.json
  server/app.js
  server/app/__tests__/index.js
  server/app/constants/index.js
  server/app/controllers/index.js
  server/app/middleware/index.js
  server/app/models/index.js
  server/app/routes/index.js
  server/bin/www
  server/package.json
  yarn.lock
Labels: setup

#9 Eslint Husky Setup Completed
  .eslintrc.json
  package-lock.json
  package.json
  yarn.lock
Labels: setup

#15 setup: Jest for client and server
  client/package.json
  client/src/__tests__/App.test.js
  client/src/__tests__/index.test.js
  client/src/index.test.js
  client/src/setupTests.js
  client/src/views/index.js
  client/yarn.lock
  package.json
  server/app/models/index.js
  server/bin/www
  server/jest.config.js
  server/package.json
  server/src/__tests__/app.test.js
  server/src/app.js
  server/src/constants/index.js
  server/src/controllers/index.js
  server/src/middleware/index.js
  server/src/models/index.js
  server/src/routes/index.js
  yarn.lock
Labels: setup

#23 [fix] packagejson update of missing module
  server/package.json
  server/src/app.js
  yarn.lock
Labels: needs-final-review

#18 Configure Babel To Server
  .eslintrc.json
  .gitignore
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/src/assets/css/App.css
  client/src/components/app/App.js
  client/src/index.test.js
  package.json
  server/.babelrc
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/routes/index.js
  server/src/www.js
  yarn.lock
Labels: needs-final-review

#30 [fix] Refactored Server Tests
  client/package.json
  server/src/__tests__/app.test.js
Labels: bug, needs-final-review

#26 [feat] Add Issue and PR templates
  ISSUE_TEMPLATE/bug_report.md
  ISSUE_TEMPLATE/feature_request.md
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement, needs-final-review

#20 Setup generic component for MaterialUI combobox
  client/package.json
  client/public/index.html
  client/src/components/Generic/Menu/Menu.js
  client/src/components/Generic/index.js
  client/src/components/Theme/theme.js
  client/src/components/app/App.js
  client/src/components/app/App.module.css
  client/src/index.js
  yarn.lock
Labels: enhancement, needs-final-review

#34 [feat] Implement WorkSpace Component
  client/package.json
  client/public/logo.png
  client/src/assets/css/App.css
  client/src/components/Amenities/Amenities.js
  client/src/components/Amenities/Amenities.module.css
  client/src/components/Generic/Box/Box.js
  client/src/components/Generic/Button/Button.js
  client/src/components/Generic/Carousel/Carousel.js
  client/src/components/Generic/Checkbox/Checkbox.js
  client/src/components/Generic/Grid/Grid.js
  client/src/components/Generic/Loader/Loader.js
  client/src/components/Generic/Modal/Modal.js
  client/src/components/Generic/TextField/TextField.js
  client/src/components/Generic/index.js
  client/src/components/Theme/theme.js
  client/src/components/WorkSpaceCard/WorkSpace.module.css
  client/src/components/WorkSpaceCard/index.js
  client/src/components/app/App.js
  client/src/components/app/App.module.css
  package-lock.json
  yarn.lock
Labels: enhancement

#16 Setup generic components from MaterialUI
  client/src/components/Generic/Box/Box.js
  client/src/components/Generic/Button/Button.js
  client/src/components/Generic/Checkbox/Checkbox.js
  client/src/components/Generic/Grid/Grid.js
  client/src/components/Generic/Loader/Loader.js
  client/src/components/Generic/Modal/Modal.js
  client/src/components/Generic/TextField/TextField.js
  client/src/components/Generic/index.js
  client/src/components/app/App.js
  server/src/routes/users.js
Labels: enhancement

#28 [feat] Add License file to repo
  LICENSE
Labels: enhancement, needs-final-review

#42 Add Logo To ReadMe.md
  README.md
Labels: documentation, needs-final-review

#41 [feat] Implement HomePage
  client/package.json
  client/public/images/bg-min.jpg
  client/src/__tests__/Homepage/index.test.js
  client/src/__tests__/index.test.js
  client/src/apis/getWorkSpace.js
  client/src/components/Amenities/Amenities.js
  client/src/components/Generic/Button/Button.js
  client/src/components/Generic/Carousel/Carousel.js
  client/src/components/WorkSpaceCard/WorkSpace.module.css
  client/src/components/app/App.js
  client/src/views/Homepage/Homepage.module.css
  client/src/views/Homepage/index.js
  client/src/views/WorkSpaceList/index.js
  yarn.lock
Labels: ui

#61 [fix] Fix lint errors
  .eslintignore
  .eslintrc.json
  .prettierrc
  client/README.md
  client/package.json
  client/src/components/Amenities/Amenities.js
  client/src/components/Generic/Menu/Menu.js
  client/src/components/Theme/theme.js
  client/src/components/WorkSpaceCard/index.js
  client/src/components/app/App.js
  client/src/index.js
  client/src/index.test.js
  client/src/setupTests.js
  client/src/views/index.js
  package.json
  server/jest.config.js
  server/src/__tests__/app.test.js
  server/src/__tests__/user.test.js
  server/src/app.js
  server/src/constants/db.js
  server/src/constants/port.js
  server/src/constants/routes.js
  server/src/constants/token.js
  server/src/controllers/users.js
  server/src/db/index.js
  server/src/middleware/auth.js
  server/src/models/user.js
  server/src/routes/index.js
  server/src/routes/router.js
  server/src/routes/users.js
  server/src/server.js
  server/src/www.js
  yarn.lock
Labels: bug, needs-final-review, setup

#10 Setup of CI/CD
  .circleci/config.yml
  Procfile
  client/package.json
  setup_heroku.sh
Labels: needs-final-review, setup

#50 [Enhancement] Cookies setup for JWT
  .eslintrc.json
  server/src/__tests__/app.test.js
  server/src/__tests__/user.test.js
  server/src/constants/routes.js
  server/src/constants/token.js
  server/src/controllers/users.js
  server/src/middleware/auth.js
  server/src/models/user.js
  server/src/routes/users.js
  server/src/server.js
Labels: enhancement

#37 [Feat] Logger using log4js lib in express.
  server/src/constants/prod.js
  server/src/logger/logger.js
Labels: enhancement

#58 Booking Api's
  server/package.json
  server/src/__tests__/app.test.js
  server/src/__tests__/booking.test.js
  server/src/__tests__/user.test.js
  server/src/constants/db.js
  server/src/constants/routes.js
  server/src/controllers/bookings.js
  server/src/middleware/camelcase.js
  server/src/middleware/isCustomer.js
  server/src/models/booking.js
  server/src/models/index.js
  server/src/routes/bookings.js
  server/src/routes/router.js
Labels: needs-final-review

#39 [feat] Added Navbar component
  client/src/__tests__/Navbar/index.test.js
  client/src/components/Generic/Button/Button.js
  client/src/components/Navbar/Navbar.js
  client/src/components/Navbar/Navbar.module.css
  client/src/components/app/App.js
  client/src/components/icons.js
  client/src/views/index.js
Labels: enhancement, needs-final-review, ui

#63 [feat] Add Login View
  client/package.json
  client/src/components/app/App.js
  client/src/components/app/App.module.css
  client/src/components/icons.js
  client/src/index.js
  client/src/views/Login/Login.js
  client/src/views/Login/Login.module.css
  client/src/views/index.js
  yarn.lock
Labels: enhancement, needs-final-review, ui

#67 [feat] Implement Rooms Component & Views
  client/.gitignore
  client/package.json
  client/public/index.html
  client/src/__tests__/Homepage/index.test.js
  client/src/__tests__/WorkspaceList/index.test.js
  client/src/apis/getRooms.js
  client/src/apis/getWorkSpace.js
  client/src/components/FilterPanel/FilterChecks.js
  client/src/components/FilterPanel/index.js
  client/src/components/Generic/Checkbox/Checkbox.js
  client/src/components/Generic/Checkbox/index.js
  client/src/components/Generic/FormControlLabel/index.js
  client/src/components/Generic/Popover/index.js
  client/src/components/Generic/ProgressBar/LinearProgress.js
  client/src/components/Generic/index.js
  client/src/components/OpeningHours/index.js
  client/src/components/RoomCard/Room.module.css
  client/src/components/RoomCard/index.js
  client/src/components/WorkSpaceCard/index.js
  client/src/components/app/App.js
  client/src/constants/index.js
  client/src/containers/index.js
  client/src/containers/room.js
  client/src/containers/workspace.js
  client/src/utils/QueryKeyValue.js
  client/src/views/Homepage/index.js
  client/src/views/RoomList/RoomList.module.css
  client/src/views/RoomList/index.js
  client/src/views/WorkSpaceList/index.js
  server/package.json
  server/src/__tests__/controller/workspace.test.js
  server/src/app.js
  server/src/controllers/workspace.js
  server/src/models/location.js
  yarn.lock
Labels: needs-final-review

#73 [feat] Integrate Login API
  client/src/apis/auth.js
  client/src/apis/axios_hoc.js
  client/src/apis/getRooms.js
  client/src/apis/getWorkSpace.js
  client/src/components/Navbar/Navbar.js
  client/src/components/app/App.js
  client/src/constants/index.js
  client/src/index.js
  client/src/store/authContext.js
  client/src/views/Login/Login.js
Labels: apis, enhancement, ui

#59 View of Workspace list after search
  client/src/__tests__/Homepage/index.test.js
  client/src/apis/getWorkSpace.js
  client/src/components/FilterPanel/index.js
  client/src/containers/workspace.js
  client/src/views/WorkSpaceList/index.js
Labels: needs-final-review

#66 [Feat] Workspace integration
  client/src/__tests__/Homepage/index.test.js
  client/src/apis/auth.js
  client/src/apis/getRooms.js
  client/src/apis/getWorkSpace.js
  client/src/components/Amenities/Amenities.js
  client/src/components/FilterPanel/FilterChecks.js
  client/src/components/FilterPanel/index.js
  client/src/components/OpeningHours/index.js
  client/src/components/WorkSpaceCard/WorkSpace.module.css
  client/src/components/WorkSpaceCard/index.js
  client/src/components/app/App.js
  client/src/constants/index.js
  client/src/containers/workspace.js
  client/src/views/WorkSpaceList/index.js
  server/src/__tests__/controller/workspace.test.js
  server/src/__tests__/user.test.js
  server/src/controllers/users.js
  server/src/controllers/workspace.js
  server/src/models/user.js
  server/src/routes/workspace.js
Labels: needs-final-review

#78 [feat] Integrate SignUp with APIs
  client/src/apis/auth.js
  client/src/apis/getRooms.js
  client/src/apis/getWorkSpace.js
  client/src/apis/signup.js
  client/src/components/app/App.js
  client/src/constants/index.js
  client/src/index.js
  client/src/views/Login/Login.js
  client/src/views/Login/Login.module.css
Labels: enhancement, ui

#83 [feat] Adding navbar api integrations
  .eslintignore
  client/src/apis/auth.js
  client/src/components/Navbar/Navbar.js
  client/src/components/Navbar/Navbar.module.css
  client/src/index.js
  client/src/views/Homepage/Homepage.module.css
  client/src/views/Login/Login.js
Labels: enhancement, needs-final-review
